# frozen_string_literal: true

module Analysis
  class MockGenerationClient
    def analyze(source_chunks:, related_chunks: [])
      chunk = source_chunks.first
      excerpt = chunk&.content.to_s.squish.truncate(180)
      cited_chunk_id = chunk&.chunk_id

      {
        concepts: [
          {
            name: "Development Concept",
            definition: excerpt.presence || "Generated by the development analysis mock.",
            classification: "supporting",
            why_it_matters: "This placeholder keeps the processing pipeline runnable without an external AI API.",
            cited_chunk_ids: Array(cited_chunk_id).compact
          }
        ],
        questions: [
          {
            tier: 1,
            tier_name: "Recall",
            text: "What is this selection mainly about?",
            answer: excerpt.presence || "The selection has no extracted content.",
            cited_chunk_ids: Array(cited_chunk_id).compact
          }
        ],
        quotes: [
          {
            text: excerpt.presence || "No quote available.",
            note: related_chunks.any? ? "Related source context was available." : nil,
            cited_chunk_ids: Array(cited_chunk_id).compact
          }
        ]
      }
    end
  end
end
