/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as AuthedRouteRouteImport } from './routes/_authed/route'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as AuthedSourcesIndexRouteImport } from './routes/_authed/sources/index'
import { Route as ApiTrpcSplatRouteImport } from './routes/api.trpc.$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthedSourcesSourceIdRouteImport } from './routes/_authed/sources/$sourceId'
import { Route as AuthedSourcesNewRouteRouteImport } from './routes/_authed/sources/new/route'

const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRouteRoute = AuthedRouteRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedSourcesIndexRoute = AuthedSourcesIndexRouteImport.update({
  id: '/sources/',
  path: '/sources/',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedSourcesSourceIdRoute = AuthedSourcesSourceIdRouteImport.update({
  id: '/sources/$sourceId',
  path: '/sources/$sourceId',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedSourcesNewRouteRoute = AuthedSourcesNewRouteRouteImport.update({
  id: '/sources/new',
  path: '/sources/new',
  getParentRoute: () => AuthedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/auth': typeof AuthRouteRoute
  '/sources/new': typeof AuthedSourcesNewRouteRoute
  '/sources/$sourceId': typeof AuthedSourcesSourceIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/sources/': typeof AuthedSourcesIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRouteRoute
  '/': typeof AuthedIndexRoute
  '/sources/new': typeof AuthedSourcesNewRouteRoute
  '/sources/$sourceId': typeof AuthedSourcesSourceIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/sources': typeof AuthedSourcesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteRouteWithChildren
  '/auth': typeof AuthRouteRoute
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/sources/new': typeof AuthedSourcesNewRouteRoute
  '/_authed/sources/$sourceId': typeof AuthedSourcesSourceIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/_authed/sources/': typeof AuthedSourcesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/sources/new'
    | '/sources/$sourceId'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/sources/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/'
    | '/sources/new'
    | '/sources/$sourceId'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/sources'
  id:
    | '__root__'
    | '/_authed'
    | '/auth'
    | '/_authed/'
    | '/_authed/sources/new'
    | '/_authed/sources/$sourceId'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/_authed/sources/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRouteRoute: typeof AuthedRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/sources/': {
      id: '/_authed/sources/'
      path: '/sources'
      fullPath: '/sources/'
      preLoaderRoute: typeof AuthedSourcesIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/sources/$sourceId': {
      id: '/_authed/sources/$sourceId'
      path: '/sources/$sourceId'
      fullPath: '/sources/$sourceId'
      preLoaderRoute: typeof AuthedSourcesSourceIdRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/sources/new': {
      id: '/_authed/sources/new'
      path: '/sources/new'
      fullPath: '/sources/new'
      preLoaderRoute: typeof AuthedSourcesNewRouteRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
  }
}

interface AuthedRouteRouteChildren {
  AuthedIndexRoute: typeof AuthedIndexRoute
  AuthedSourcesNewRouteRoute: typeof AuthedSourcesNewRouteRoute
  AuthedSourcesSourceIdRoute: typeof AuthedSourcesSourceIdRoute
  AuthedSourcesIndexRoute: typeof AuthedSourcesIndexRoute
}

const AuthedRouteRouteChildren: AuthedRouteRouteChildren = {
  AuthedIndexRoute: AuthedIndexRoute,
  AuthedSourcesNewRouteRoute: AuthedSourcesNewRouteRoute,
  AuthedSourcesSourceIdRoute: AuthedSourcesSourceIdRoute,
  AuthedSourcesIndexRoute: AuthedSourcesIndexRoute,
}

const AuthedRouteRouteWithChildren = AuthedRouteRoute._addFileChildren(
  AuthedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthedRouteRoute: AuthedRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
