/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as AuthedRouteRouteImport } from './routes/_authed/route'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as AuthedSourcesIndexRouteImport } from './routes/_authed/sources/index'
import { Route as ApiTrpcSplatRouteImport } from './routes/api.trpc.$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthedSettingsProvidersRouteImport } from './routes/_authed/settings/providers'
import { Route as AuthedSourcesNewRouteRouteImport } from './routes/_authed/sources/new/route'
import { Route as AuthedSourcesSourceIdRouteRouteImport } from './routes/_authed/sources/$sourceId/route'
import { Route as AuthedSourcesSourceIdIndexRouteImport } from './routes/_authed/sources/$sourceId/index'
import { Route as AuthedSourcesSourceIdSelectionsSelectionIdRouteRouteImport } from './routes/_authed/sources/$sourceId/selections/$selectionId/route'

const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRouteRoute = AuthedRouteRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedSourcesIndexRoute = AuthedSourcesIndexRouteImport.update({
  id: '/sources/',
  path: '/sources/',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedSettingsProvidersRoute = AuthedSettingsProvidersRouteImport.update({
  id: '/settings/providers',
  path: '/settings/providers',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedSourcesNewRouteRoute = AuthedSourcesNewRouteRouteImport.update({
  id: '/sources/new',
  path: '/sources/new',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedSourcesSourceIdRouteRoute =
  AuthedSourcesSourceIdRouteRouteImport.update({
    id: '/sources/$sourceId',
    path: '/sources/$sourceId',
    getParentRoute: () => AuthedRouteRoute,
  } as any)
const AuthedSourcesSourceIdIndexRoute =
  AuthedSourcesSourceIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedSourcesSourceIdRouteRoute,
  } as any)
const AuthedSourcesSourceIdSelectionsSelectionIdRouteRoute =
  AuthedSourcesSourceIdSelectionsSelectionIdRouteRouteImport.update({
    id: '/selections/$selectionId',
    path: '/selections/$selectionId',
    getParentRoute: () => AuthedSourcesSourceIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/auth': typeof AuthRouteRoute
  '/sources/$sourceId': typeof AuthedSourcesSourceIdRouteRouteWithChildren
  '/sources/new': typeof AuthedSourcesNewRouteRoute
  '/settings/providers': typeof AuthedSettingsProvidersRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/sources/': typeof AuthedSourcesIndexRoute
  '/sources/$sourceId/': typeof AuthedSourcesSourceIdIndexRoute
  '/sources/$sourceId/selections/$selectionId': typeof AuthedSourcesSourceIdSelectionsSelectionIdRouteRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRouteRoute
  '/': typeof AuthedIndexRoute
  '/sources/new': typeof AuthedSourcesNewRouteRoute
  '/settings/providers': typeof AuthedSettingsProvidersRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/sources': typeof AuthedSourcesIndexRoute
  '/sources/$sourceId': typeof AuthedSourcesSourceIdIndexRoute
  '/sources/$sourceId/selections/$selectionId': typeof AuthedSourcesSourceIdSelectionsSelectionIdRouteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteRouteWithChildren
  '/auth': typeof AuthRouteRoute
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/sources/$sourceId': typeof AuthedSourcesSourceIdRouteRouteWithChildren
  '/_authed/sources/new': typeof AuthedSourcesNewRouteRoute
  '/_authed/settings/providers': typeof AuthedSettingsProvidersRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/_authed/sources/': typeof AuthedSourcesIndexRoute
  '/_authed/sources/$sourceId/': typeof AuthedSourcesSourceIdIndexRoute
  '/_authed/sources/$sourceId/selections/$selectionId': typeof AuthedSourcesSourceIdSelectionsSelectionIdRouteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/sources/$sourceId'
    | '/sources/new'
    | '/settings/providers'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/sources/'
    | '/sources/$sourceId/'
    | '/sources/$sourceId/selections/$selectionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/'
    | '/sources/new'
    | '/settings/providers'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/sources'
    | '/sources/$sourceId'
    | '/sources/$sourceId/selections/$selectionId'
  id:
    | '__root__'
    | '/_authed'
    | '/auth'
    | '/_authed/'
    | '/_authed/sources/$sourceId'
    | '/_authed/sources/new'
    | '/_authed/settings/providers'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/_authed/sources/'
    | '/_authed/sources/$sourceId/'
    | '/_authed/sources/$sourceId/selections/$selectionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRouteRoute: typeof AuthedRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/sources/': {
      id: '/_authed/sources/'
      path: '/sources'
      fullPath: '/sources/'
      preLoaderRoute: typeof AuthedSourcesIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/settings/providers': {
      id: '/_authed/settings/providers'
      path: '/settings/providers'
      fullPath: '/settings/providers'
      preLoaderRoute: typeof AuthedSettingsProvidersRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/sources/new': {
      id: '/_authed/sources/new'
      path: '/sources/new'
      fullPath: '/sources/new'
      preLoaderRoute: typeof AuthedSourcesNewRouteRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/sources/$sourceId': {
      id: '/_authed/sources/$sourceId'
      path: '/sources/$sourceId'
      fullPath: '/sources/$sourceId'
      preLoaderRoute: typeof AuthedSourcesSourceIdRouteRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/sources/$sourceId/': {
      id: '/_authed/sources/$sourceId/'
      path: '/'
      fullPath: '/sources/$sourceId/'
      preLoaderRoute: typeof AuthedSourcesSourceIdIndexRouteImport
      parentRoute: typeof AuthedSourcesSourceIdRouteRoute
    }
    '/_authed/sources/$sourceId/selections/$selectionId': {
      id: '/_authed/sources/$sourceId/selections/$selectionId'
      path: '/selections/$selectionId'
      fullPath: '/sources/$sourceId/selections/$selectionId'
      preLoaderRoute: typeof AuthedSourcesSourceIdSelectionsSelectionIdRouteRouteImport
      parentRoute: typeof AuthedSourcesSourceIdRouteRoute
    }
  }
}

interface AuthedSourcesSourceIdRouteRouteChildren {
  AuthedSourcesSourceIdIndexRoute: typeof AuthedSourcesSourceIdIndexRoute
  AuthedSourcesSourceIdSelectionsSelectionIdRouteRoute: typeof AuthedSourcesSourceIdSelectionsSelectionIdRouteRoute
}

const AuthedSourcesSourceIdRouteRouteChildren: AuthedSourcesSourceIdRouteRouteChildren =
  {
    AuthedSourcesSourceIdIndexRoute: AuthedSourcesSourceIdIndexRoute,
    AuthedSourcesSourceIdSelectionsSelectionIdRouteRoute:
      AuthedSourcesSourceIdSelectionsSelectionIdRouteRoute,
  }

const AuthedSourcesSourceIdRouteRouteWithChildren =
  AuthedSourcesSourceIdRouteRoute._addFileChildren(
    AuthedSourcesSourceIdRouteRouteChildren,
  )

interface AuthedRouteRouteChildren {
  AuthedIndexRoute: typeof AuthedIndexRoute
  AuthedSourcesSourceIdRouteRoute: typeof AuthedSourcesSourceIdRouteRouteWithChildren
  AuthedSourcesNewRouteRoute: typeof AuthedSourcesNewRouteRoute
  AuthedSettingsProvidersRoute: typeof AuthedSettingsProvidersRoute
  AuthedSourcesIndexRoute: typeof AuthedSourcesIndexRoute
}

const AuthedRouteRouteChildren: AuthedRouteRouteChildren = {
  AuthedIndexRoute: AuthedIndexRoute,
  AuthedSourcesSourceIdRouteRoute: AuthedSourcesSourceIdRouteRouteWithChildren,
  AuthedSourcesNewRouteRoute: AuthedSourcesNewRouteRoute,
  AuthedSettingsProvidersRoute: AuthedSettingsProvidersRoute,
  AuthedSourcesIndexRoute: AuthedSourcesIndexRoute,
}

const AuthedRouteRouteWithChildren = AuthedRouteRoute._addFileChildren(
  AuthedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthedRouteRoute: AuthedRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
